# Lint with https://config.travis-ci.org/
dist: bionic
language: crystal
os: linux
install:
- shards install
jobs:
  include:
  - script: crystal spec
  - script: bin/ameba
notifications:
  slack:
    secure: ZhQxfokt4+2tNoEc95pOIlk9FfDwZfN833bIE8dFPAPwYv1ECRnHeVNneRfj5O01+iED7126ikbB4I8p6FazU2DqLg7haHb4f9yC+ie726M0/RPwH8dbJOJMFjbEfxo4bsL2qln89rE3DKCqlS4crGu9FUa3qJs/QWScWS14AOsOtevheuYGmKXmpPiHC4s4+7j7ZQfxt2RIZ11LVePfukcb1SmRTIozt+nM0NJB3ZkeOCDb7IcWs2wUjp3Vr9mFNR2WSfw4vRt15DtgdENx1zmw8o42sLv7mFwDYtgUavU04jtXB0f+WNL2+T/SlM0k0d5xbhwOlQB3Jxkn4rRWR5iLDnT+QWoukEiAkgW/w9n9odlCZIZ3fRkKz6v6lqaZTmgj2MnIaw9VmIsgra7qfcuRSfTgU4/JNB80TvSyrTvLKzqUcvTqwzrjHqwjRGxZUgSxRcPszhkNUwn0KPRCyswgeInINMxaNlNUOXi61j0ApZb7av4FJMGUEvE1K5Afrvafe1tyO7SlAitWFXabH+76gaBZRkvBNvEs4cK6fuKj5K4br9OAhyMWwQAyBHIjjFvjFdOnUqwOZoafJkaHbUCGMErNhAlxWLjMHVDmPkfWu0inYEoIfD9+zp77yw6hisdPjDc3SnUpSN/ICwLxqhOrGhrhHy7gmbIrl8y8fy8=
