name: avalanchemq
base: core18
version: git
summary: Lean and mean AMQP server # 79 char long summary
description: |
  An high throughput, advanced message queue server.

grade: devel # devel or stable
confinement: strict

apps:
  server:
    command: avalanchemq -D $SNAP_DATA
    daemon: simple
    plugs:
      - network
      - network-bind
  perf:
    command: avalanchemqperf
    plugs:
      - network

parts:
  avalanchemq:
    plugin: crystal
    crystal-build-options:
      - --release
    source: .
    build-packages:
      - git
      - libssl-dev
      - libevent-dev
