name: CI
on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: crystallang/crystal:0.35.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Crystal Ameba Linter
        uses: crystal-ameba/github-action@v0.2.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  spec:
    name: Spec
    runs-on: ubuntu-latest
    container: crystallang/crystal:0.35.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Shards install
        run: shards install

      - name: Spec
        run: crystal spec --no-color --order random

  java-client-test:
    name: RabbitMQ java client test
    runs-on: ubuntu-latest
    container: crystallang/crystal:0.35.1

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jre

      - name: Clone java client
        run: git clone https://github.com/rabbitmq/rabbitmq-java-client.git

      - name: Install dependencies
        run: apt-get install -y libsystemd-dev

      - name: Build avalanchemq
        run: shards build avalanchemq

      - name: Run avalanchemq in background
        run: bin/avalanchemq --data-dir /tmp/amqp &

      - name: Run java tests
        run: cd rabbitmq-java-client && ./mvnw verify -P '!setup-test-cluster' -Dit.test=FunctionalTests
