name: CI
on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: crystallang/crystal:0.35.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Crystal Ameba Linter
        uses: crystal-ameba/github-action@v0.2.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  spec:
    name: Spec
    runs-on: ubuntu-latest
    container: crystallang/crystal:0.35.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Shards install
        run: shards install

      - name: Spec
        run: crystal spec --no-color --order random

  java-client-test:
    name: RabbitMQ java client test
    runs-on: ubuntu-20.04

    steps:
      - name: Install dependencies
        run: sudo apt-get install -y libsystemd-dev openjdk-11-jre-headless gcc pkg-config git tzdata libpcre3-dev libevent-dev libyaml-dev libgmp-dev libssl-dev libxml2-dev python-is-python3 python3

      - name: Install Crystal
        run: sudo snap install crystal --classic

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build avalanchemq
        run: |
          crystal --version
          shards --version
          shards install --production
          shards build --production avalanchemq

      - name: Run avalanchemq in background
        run: bin/avalanchemq --data-dir /tmp/amqp &

      - name: Clone java client
        run: git clone --depth 1 https://github.com/84codes/rabbitmq-java-client.git

      - name: Run java tests
        run: |
          cd rabbitmq-java-client
          make deps
          ./mvnw verify -P '!setup-test-cluster' -Dit.test=FunctionalTests
