name: Clean up PR artifacts
on:
  pull_request:
    types: [closed]

jobs:
  delete-docker-hub-pr:
    name: Delete Docker hub PR image
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        env:
          CREDS: "{ \"username\": \"${{ secrets.DOCKERHUB_USERNAME }}\", \"password\": \"${{ secrets.DOCKERHUB_TOKEN }}\" }"
        run: |
          curl -s -H "Content-Type: application/json" -XPOST -d "$CREDS" \
            https://hub.docker.com/v2/users/login/ | \
          jq -r '"TOKEN=" + (.token)' >> $GITHUB_ENV
      - name: Delete PR tag
        env:
          TAG: pr-${{ github.event.number }}
        run: |
          curl -XDELETE -H "Authorization: JWT ${TOKEN}" \
            "https://hub.docker.com/v2/repositories/cloudamqp/lavinmq/tags/${TAG}/"
