on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        run: git clone ${{ github.repositoryUrl }} .

      - name: Create Release
        run: gh release create "${{ github.ref }}" --notes "$(./build/release_notes)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
