on:
  push:
    tags:
      - v*
  workflow_dispatch:

name: Create Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Release
        run: gh release create "${{ github.ref }}" --notes "$(./generate-release-notes)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
