on:
  push:
    tags:
      - v*

name: Create Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        run: git clone ${{ github.repositoryUrl }} .

      - name: Create Release
        run: gh release create "${{ github.ref }}" --notes "$(./generate-release-notes)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
