name: RPM
on:
  pull_request:
    paths:
      - .github/workflows/rpm.yml
      - Dockerfile.rpm
      - build/lavinmq.spec
      - shard.lock
      - src/**
      - static/**
      - openapi/**
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
    paths:
      - .github/workflows/rpm.yml
      - Dockerfile.rpm
      - build/lavinmq.spec
      - shard.lock
      - src/**
      - static/**
      - openapi/**
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build_rpm:
    name: Build RPM
    strategy:
      matrix:
        os: ['fedora-37']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build deb package
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha,scope=${{ github.workflow }}-${{ matrix.os }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}-${{ matrix.os }}
          file: Dockerfile.rpm
          platforms: linux/amd64,linux/arm64
          build-args: |
            build_image=84codes/crystal:1.6.2-${{ matrix.os }}
          outputs: RPMS

      - uses: actions/upload-artifact@v3
        name: Upload artifact
        with:
          name: rpm-packages
          path: RPMS

      - name: Upload to Packagecloud
        run: |
          set -eux
          curl -fsSO -u "${{ secrets.packagecloud_token }}:" https://packagecloud.io/api/v1/distributions.json
          ID=$(echo "${{ matrix.os }}" | cut -d- -f1)
          VERSION_ID=$(echo "${{ matrix.os }}" | cut -d- -f2)
          DIST_ID=$(jq ".rpm[] | select(.index_name == \"${ID}\").versions[] | select(.index_name == \"${VERSION_ID}\").id" distributions.json)
          for PKG_FILE in $(find RPMS -name "*.rpm")
          do curl -fsS -u "${{ secrets.packagecloud_token }}:" -XPOST \
                  -F "package[distro_version_id]=${DIST_ID}" \
                  -F "package[package_file]=@${PKG_FILE}" \
                  https://packagecloud.io/api/v1/repos/${{ github.repository }}/packages.json
          done
        if: startsWith(github.ref, 'refs/tags/v')

      - name: Upload to Packagecloud head repo
        run: |
          set -eux
          curl -fsSO -u "${{ secrets.packagecloud_token }}:" https://packagecloud.io/api/v1/distributions.json
          ID=$(echo "${{ matrix.os }}" | cut -d- -f1)
          VERSION_ID=$(echo "${{ matrix.os }}" | cut -d- -f2)
          DIST_ID=$(jq ".rpm[] | select(.index_name == \"${ID}\").versions[] | select(.index_name == \"${VERSION_ID}\").id" distributions.json)
          for PKG_FILE in $(find RPMS -name "*.rpm")
          do curl -fsS -u "${{ secrets.packagecloud_token }}:" -XPOST \
                  -F "package[distro_version_id]=${DIST_ID}" \
                  -F "package[package_file]=@${PKG_FILE}" \
                  https://packagecloud.io/api/v1/repos/${{ github.repository }}-head/packages.json
          done
        if: github.ref == 'refs/heads/main'
